### ISSUE TITLE
Add gzip compression on live server

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/PatientManagement_Admin#46]
https://varvy.com/pagespeed/enable-compression.html

**Comment by Magik3a** [comment]
.htaccess compression is only applicable for us neither the NGINX compression because we dont use linux or apache servers. When the public site is having project file and is included in the current solution, i will enable it thru azure web service 
http://www.brandonmartinez.com/2015/08/20/enable-gzip-compression-for-azure-web-apps/
